CREATE  DATABASE IF NOT EXISTS KabumTega;

USE KabumTega;


CREATE TABLE IF NOT EXISTS Cliente (
Id_cliente BIGINT AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
Email VARCHAR(100) NOT NULL,
CPF VARCHAR(15),
Senha VARCHAR(100) NOT NULL,
Nome VARCHAR(100),
RG VARCHAR(15),
Idade INT,
DataDeNascimento VARCHAR (20),
Foto VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Endereco (
Id_endereco BIGINT AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
Estado VARCHAR(2) NOT NULL,
Endereco  VARCHAR(100),
Cidade VARCHAR(50) NOT NULL,
CEP BIGINT,
Id_cliente BIGINT NOT NULL,
FOREIGN KEY(Id_cliente) REFERENCES Cliente(Id_cliente)
ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Produto (
Id_produto BIGINT AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
Quantidade INT,
Descricao VARCHAR(255) NOT NULL,
Preço DECIMAL(10,2) NOT NULL
);


CREATE TABLE IF NOT EXISTS Suporte (
Id_suporte BIGINT AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
Nome VARCHAR(2),
Idade INT,
Data_de_Entrada DATE,
CPF VARCHAR(15),
RG VARCHAR(15),
Salário DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS Interage (
Id_interage BIGINT AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
Id_cliente BIGINT,
Id_suporte BIGINT,
FOREIGN KEY(Id_cliente) REFERENCES Cliente (Id_cliente),
FOREIGN KEY(Id_suporte) REFERENCES Suporte (Id_suporte)
);

CREATE TABLE IF NOT EXISTS Compra (
Id_compra BIGINT AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
Id_cliente BIGINT,
Id_produto BIGINT,
DATA_da_Compra DATE,
FOREIGN KEY(Id_cliente) REFERENCES Cliente (Id_cliente),
FOREIGN KEY(Id_produto) REFERENCES Produto (Id_produto)
)


